### PR TITLE
Rename test files for better portability across OSes

### PR DESCRIPTION
**Pull request by autayeu**
It wasn't possible to checkout the repo in Windows. This fixes and shortens file names which were illegal in Windows.

### CODE REVIEW

**Comment by mawiesne** [comment]
@rzo1 @kinow This contribution might we valuable in terms of cross-platform experience for the community. We had a similar struggle recently. Please check if you think this can be merged (no conflicts, it seems).

**Review by kinow — COMMENTED** [review]
I think the idea with these old file names was to retain some metadata for provenance. Perhaps instead of just deleting these files, we could have a `README.md` or `metadata.csv` in this `News` directory with one line per file, containing this information in a table or as a spread sheet/csv?

-Bruno

**Comment by rzo1** [comment]
> @rzo1 @kinow This contribution might we valuable in terms of cross-platform experience for the community. We had a similar struggle recently. Please check if you think this can be merged (no conflicts, it seems).

Didn't we remove the `News` file in the `opennlp-similarity` PR as they were not used? So if this branch is rebased, there shouldn't be any changes left.

**Comment by mawiesne** [comment]
> So if this branch is rebased, there shouldn't be any changes left.

@rzo1 Seems correct. 

@autayeu I'll close your PR as it was superseded by #79 in which the problem you described here was fixed.

**Pull request closed without merging**
