### PR TITLE
Update sandbox components to use opennlp-tools version 2.1.1

### PR DESCRIPTION
**Pull request by mawiesne**
Thank you for contributing to Apache OpenNLP.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with OPENNLP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically main)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn clean install` at the root opennlp-sandbox folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file in opennlp-sandbox folder?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found in opennlp-sandbox folder?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by kinow — COMMENTED** [review]
Huh, CI is a little unwell. Does GitHub Actions need a kick, or is 2.1.1 incompatible with the current code in opennlp-tools (or vice-versa)?

**Comment by rzo1** [comment]
Looks like compile Issues, for example:

```
2023-04-04T19:18:50.6312620Z [ERROR] /home/runner/work/opennlp-sandbox/opennlp-sandbox/mallet-addon/src/main/java/opennlp/addons/mallet/CRFTrainer.java:[60,3] method does not override or implement a method from a supertype
```

**Review by jzonthemtn — DISMISSED** [review]

**Comment by mawiesne** [comment]
Had a first look into this. Will have a look into the compatibility issue during the next days, maybe in combo with @rzo1 and ☕️. :)

**Comment by mawiesne** [comment]
@jzonthemtn @kinow @rzo1 
I fixed those compile issues, ready for review.

**Review by kinow — APPROVED** [review]

**Review by rzo1 — APPROVED** [review]

**Pull request merged**
