### PR TITLE
OPENNLP-1472 Fix flaky (sub-) test of GradientDescentUtilsTest in sandbox component 'nlp-utils'

### PR DESCRIPTION
**Pull request by mawiesne**
Change
-
- adjusts parameter alpha in GradientDescentUtilsTest from `0.00002` to `0.00001`
- aforementioned param change results in stable convergence, checked via RepeatedTest (JUnit)
- optimizes how random values are obtained in `GradientDescentUtils`
- fixes a potentially unpredictable BigDecimal value in `AnomalyDetectionUtils` (see JavaDoc of that constructor)

Tasks
-
Thank you for contributing to Apache OpenNLP.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with OPENNLP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically main)?

- [x] Is your initial contribution a single, squashed commit?

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn clean install` at the root opennlp-sandbox folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](https://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file in opennlp-sandbox folder?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file found in opennlp-sandbox folder?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Approving assuming CI will pass :tada: :crossed_fingers: 
Thanks!

**Comment by mawiesne** [comment]
> Approving assuming CI will pass 🎉 🤞

Passed, 1 run, all fine. Bonus info: Passes fine on MacOS env as well.

**Review by rzo1 — APPROVED** [review]

**Comment by mawiesne** [comment]
@jzonthemtn Could you create a new unreleased version in Jira? I'm lacking a projected fix version upon closing issues, atm.

Maybe, we could have a 2.1.2 and/or a 2.2.0 as this one might open up sooner or later.

**Comment by mawiesne** [comment]
> Could you create a new unreleased version in Jira? I'm lacking a projected fix version upon closing issues, atm.

@kinow Could you help (us) out, so I can properly merge this PR to avoid further toggle builds  and close the associated Jira properly? see ^

**Comment by kinow** [comment]
> > Could you create a new unreleased version in Jira? I'm lacking a projected fix version upon closing issues, atm.
> 
> @kinow Could you help (us) out, so I can merge this PR to avoid further toggle builds and close the associated Jira properly? see ^

Huh, I just checked the `OPENNLP` project on JIRA and I do not see the option to "Manage Versions" (as I see on Jena & Commons). I might be missing some karma on JIRA… will try to check if I need to request to INFRA or if I'm missing updating some SVN file… sorry.

**Comment by kinow** [comment]
@mawiesne , versions created :+1: 

image

**Comment by mawiesne** [comment]
> @mawiesne , versions created :+1: 

Thanks a lot, Bruno!

**Pull request merged**
